config/routes.rb
Rails.application.routes.draw do
  root :to => 'user_sessions#new'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# class User < ApplicationRecord
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    # ログインに成功するかどうか
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :users, notice: 'User was successfully created' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      # params.require(:user).permit(:email, :crypted_password, :salt)
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_message.html.slim
-if notice
  #notice.container.alert.alert-success.mt-3
    = flash[:notice]
-if alert
  #alert.container.alert.alert-danger.mt-3
    = flash[:alert]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RoR_EC
    link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    = render partial: 'layouts/navbar/main'
    = render partial: 'layouts/message'
    = yield

app/views/layouts/navbar/_main.html.slim
#nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container.text-white
    = link_to '/', class: "nav-item navbar-bland text-white" do
      | RoR_EC
    .collapse.navbar-collapse.justify-content-end
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li.nav-item.dropdown
            =link_to "#", class: "nav-link dropdown-toggle", data: {toggle: "dropdown"} do
              i.fas.fa-fw.fa-user
            .dropdown-menu.dropdown-menu-right
              = link_to edit_user_path(current_user.id), class: "dropdown-item" do
                | ユーザ情報編集
              = link_to "Logout", :logout, method: :post, class: "dropdown-item"
        - else
          li
            = link_to new_user_path, class: "nav-link" do
              | 登録
          li
            = link_to :login, class: "nav-link" do
              | ログイン

app/views/user_sessions/_form.html.slim
= form_tag user_sessions_path, :method => :post do
  .field.row.mt-3
    .col-md-4.text-right
      = label_tag :email, 'メールアドレス', class: 'col-form-label'
    .col-md-6
      = text_field_tag :email, '', class: 'form-control'
  .field.row.mt-3
    .col-md-4.text-right
      = label_tag :password, 'パスワード', class: 'col-form-label'
    .col-md-6
      = password_field_tag :password, '', class: 'form-control'
  .row.mt-3
    .col-md-6.offset-md-4
      = submit_tag "ログイン", class: 'btn btn-primary'

app/views/user_sessions/create.html.slim
h1
  | UserSessions#create
p
  | Find me in app/views/user_sessions/create.html.erb

app/views/user_sessions/destroy.html.slim
h1
  | UserSessions#destroy
p
  | Find me in app/views/user_sessions/destroy.html.erb

app/views/user_sessions/new.html.slim
.container
  .row.justify-content-md-center.mt-5
    .col-md-8.md-offset-2
      .card
        .card-header.bg-dark.text-white
          | ログイン
        .card-body
          = render 'form', user: @user

app/views/users/_form.html.slim
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      h2
        = pluralize(user.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - user.errors.full_messages.each do |message|
          li
            = message
  .field.row.mt-3
    .col-md-4.text-right
      = form.label :email, 'メールアドレス', class: 'col-form-label'
    .col-md-6
      = form.text_field :email, class: 'form-control'
  .field.row.mt-3
    .col-md-4.text-right
      = form.label :password, 'パスワード', class: 'col-form-label'
    .col-md-6
      = form.password_field :password, class: 'form-control'
  .field.row.mt-3
    .col-md-4.text-right
      = form.label :password_confirmation, 'パスワード（確認）', class: 'col-form-label'
    .col-md-6
      = form.password_field :password_confirmation, class: 'form-control'
  .row.mt-3
    .col-md-6.offset-md-4
      = link_to "キャンセル", users_path, class: 'btn btn-danger'
      = form.submit '登録', class: 'btn btn-primary'

app/views/users/edit.html.slim
.container
  .row.justify-content-md-center.mt-5
    .col-md-12
      .card
        .card-header.bg-dark.text-white
          | ユーザ情報編集
        .card-body
          = render 'form', user: @user

app/views/users/index.html.slim
.container
  .row.justify-content-md-center.mt-5
    .col-md-12
      .card
        .card-header.bg-dark.text-white
          | ユーザ一覧
        .card-body
          = link_to new_user_path, class: "btn btn-outline-dark" do
            | 新規ユーザ登録
          .table-responsive
            table.table.table-striped.mt-3
              thead
                tr
                  th
                    | Email
                  th
                    | Crypted password
                  th
                    | Salt
                  th[colspan="3"]
              tbody
                - @users.each do |user|
                  tr
                    td
                      = user.email
                    td
                      = user.crypted_password
                    td
                      = user.salt
                    td
                      = link_to user, class: "btn btn-outline-info" do
                        i.fa.fa-fw.fa-eye
                    td
                      = link_to edit_user_path(user), class: "btn btn-outline-success" do
                        i.fa.fa-fw.fa-edit
                    td
                      = link_to user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" do
                        i.fa.fa-fw.fa-trash

app/views/users/new.html.slim
.container
  .row.justify-content-md-center.mt-5
    .col-md-8.md-offset-2
      .card
        .card-header.bg-dark.text-white
          | ユーザ登録
        .card-body
          = render 'form', user: @user

app/views/users/show.html.slim
.container
  .row.justify-content-md-center.mt-5
    .col-md-12
      .card
        .card-header.bg-dark.text-white
          .row
            .col-md-10.text-left
              = link_to users_path, class: 'btn btn-sm btn-outline-success' do
                i.fas.fa-fw.fa-chevron-circle-left
              | 　ユーザ情報
            .col-md-2.text-right
              = link_to edit_user_path(@user), class: 'btn btn-sm btn-outline-success' do
                i.fa.fa-fw.fa-edit
        .card-body
          p
            strong
              | Email:
            = @user.email
          p
            strong
              | Crypted password:
            = @user.crypted_password
          p
            strong
              | Salt:
            = @user.salt